### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'bgsegm'

### ISSUE THREAD

**Issue by pinoden** [nicholaskajoh/Vehicle-Counting#13]
Hi! 
I believe that you need to update your requirements file. It didn't work for me with opencv-contrib-python==4.0.0.21, but did work with opencv-contrib-python==4.1.0.25

**Comment by nicholaskajoh** [comment]
Hi @pinoden! Thanks for the feedback. I came across a similar error some time ago but it was because I hadn't installed some system dependencies. Can you update the requirements file in a PR?

**Comment by nicholaskajoh** [comment]
Hi @pinoden! Thanks for the feedback. I came across a similar error some time ago but it was because I hadn't installed some system dependencies. I'll update it.
